#!/usr/bin/env python3

import argparse


parser = argparse.ArgumentParser()
parser.add_argument('pdb_file')
parser.add_argument('residues', nargs='+')
args=parser.parse_args()

args.residues = [x.upper() for x in args.residues]

with open(args.pdb_file) as f:
    for line in f:
        if line.startswith('ATOM  ') or line.startswith('HETATM'):
            if line[17:20].strip() in args.residues:
                print(line, end='')
