#!/usr/bin/env python3

import argparse


parser = argparse.ArgumentParser()
parser.add_argument('pdb_file')
parser.add_argument('chains', nargs='+')
args=parser.parse_args()

args.chains = [x.upper() for x in args.chains]

with open(args.pdb_file) as f:
    for line in f:
        if line.startswith('ATOM  ') or line.startswith('HETATM'):
            if line[21] in args.chains:
                print(line, end='')
